<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../Dashboard.Contracts/Dashboard.Contracts.csproj"/>
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.0"/>
    <PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" Version="3.0.5"/>
    <PackageReference Include="SourceGear.sqlite3" Version="3.53.4"/>
  </ItemGroup>
</Project>
