import React, { useCallback, useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { api, unwrap, type AgentTask, type Completion, type Pairing, type Snapshot } from './api';
import { Icon, Modal, Empty, duration, relative, sourceName } from './ui';
import { TaskCard, TaskForm } from './TaskCard';
import './styles.css';

function App(){
  const [auth,setAuth]=useState<boolean|null>(null),[key,setKey]=useState(''),[error,setError]=useState('');
  const [snapshot,setSnapshot]=useState<Snapshot|null>(null),[connection,setConnection]=useState('connecting'),[toast,setToast]=useState('');
  const [source,setSource]=useState('all'),[device,setDevice]=useState('all'),[query,setQuery]=useState(''),[limit,setLimit]=useState(5),[expanded,setExpanded]=useState(true);
  const [detail,setDetail]=useState<AgentTask|Completion|null>(null),[adding,setAdding]=useState(false),[pairing,setPairing]=useState<Pairing|null>(null),[busy,setBusy]=useState(false);
  const [settings,setSettings]=useState({minimumRunning:3,reminderCooldownMinutes:15}),[dirty,setDirty]=useState(false),[saved,setSaved]=useState('');
  const [permission,setPermission]=useState<NotificationPermission|undefined>(()=>'Notification' in window?Notification.permission:undefined);
  const [,tick]=useState(0); useEffect(()=>{const timer=setInterval(()=>tick(x=>x+1),1000);return()=>clearInterval(timer);},[]);
  useEffect(()=>{if(!toast)return;const t=setTimeout(()=>setToast(''),5000);return()=>clearTimeout(t);},[toast]);
  const accept=useCallback((s:Snapshot)=>setSnapshot(old=>old&&Date.parse(old.generatedAt)>Date.parse(s.generatedAt)?old:s),[]);
  const refresh=useCallback(async()=>{const r=await api.GET('/api/status');if(r.response.status===401){setAuth(false);return;}accept(unwrap(r));},[accept]);
  useEffect(()=>{void api.GET('/api/auth/status').then(r=>setAuth(unwrap(r).authenticated)).catch(e=>setError(String(e)));},[]);
  useEffect(()=>{if(!auth)return;void refresh().catch(e=>setToast(String(e)));const events=new EventSource('/api/events');
    events.onopen=()=>setConnection('live');events.onerror=()=>{setConnection('offline');void api.GET('/api/auth/status').then(r=>{if(!unwrap(r).authenticated)setAuth(false);}).catch(()=>{});};
    events.addEventListener('snapshot',e=>{accept(JSON.parse(e.data) as Snapshot);setConnection('live');});
    events.addEventListener('reminder',e=>{const r=JSON.parse(e.data) as {message:string};setToast(r.message);if('Notification' in window&&Notification.permission==='granted')try{new Notification('Below your task minimum',{body:r.message});}catch{}});
    return()=>events.close();},[auth,accept,refresh]);
  useEffect(()=>{if(snapshot&&!dirty)setSettings({minimumRunning:Number(snapshot.settings.minimumRunning),reminderCooldownMinutes:Number(snapshot.settings.reminderCooldownMinutes)});},[snapshot,dirty]);
  const run=async(fn:()=>Promise<unknown>)=>{setBusy(true);try{await fn();await refresh();}catch(e){setToast(e instanceof Error?e.message:String(e));}finally{setBusy(false);}};
  const closeDetail=useCallback(()=>setDetail(null),[]),closeAdd=useCallback(()=>setAdding(false),[]),closePair=useCallback(()=>setPairing(null),[]);
  const match=(t:AgentTask)=>(source==='all'||t.source===source)&&(device==='all'||t.deviceId===device)&&[t.title,t.workspace,t.deviceName,t.latestOutput,sourceName(t.source)].join(' ').toLowerCase().includes(query.toLowerCase());
  const tasks=snapshot?.tasks??[],completions=snapshot?.completions??[],devices=snapshot?.devices??[];
  const running=tasks.filter(t=>t.status==='running'&&match(t)),unknown=tasks.filter(t=>t.status==='unknown'&&match(t));
  const done=[...completions].filter(match).sort((a,b)=>Date.parse(b.completedAt??'')-Date.parse(a.completedAt??''));
  const total=Number(snapshot?.runningCount??0),minimum=Number(snapshot?.minimumRunning??3),missing=Math.max(0,minimum-total),extra=Math.max(0,total-minimum);
  if(auth===null||!auth)return <main className="sign-in"><span className="brand-mark"><Icon kind="brand"/></span><h1>Agent Dashboard</h1><p>Sign in with this service’s access key.</p><form onSubmit={e=>{e.preventDefault();setBusy(true);void api.POST('/api/auth/login',{body:{accessKey:key}}).then(unwrap).then(()=>{setKey('');setAuth(true);setError('');}).catch(e=>setError(String(e))).finally(()=>setBusy(false));}}><label>Access key<input type="password" value={key} onChange={e=>setKey(e.target.value)} autoComplete="current-password" required/></label><button className="button button-primary" disabled={busy}>Sign in</button><p role="alert">{error}</p></form><p className="section-description">The host stores its key in data/ui-access-key. Your session stays in an HTTP-only cookie.</p></main>;
  return <><a className="skip-link" href="#main">Skip to dashboard</a><aside className="sidebar"><a className="brand" href="#overview"><span className="brand-mark"><Icon kind="brand"/></span><span>agent<span className="brand-secondary">dashboard</span></span></a><div className="workspace-label"><Icon kind="grid"/><div>Central workspace<small>{devices.length} devices</small></div></div><p className="nav-label">WORKSPACE</p><nav><a className="nav-link active" href="#overview"><Icon kind="grid"/>Overview</a><a className="nav-link" href="#completed-panel" onClick={()=>setExpanded(true)}><Icon kind="inbox"/>Completed<span className="nav-count">{completions.length}</span></a><a className="nav-link" href="#settings-panel"><Icon kind="sliders"/>Preferences</a></nav><div className="sidebar-note"><p>Make room for<br/>the next good idea.</p><span>Keep your agents in motion.</span></div><div className="sidebar-footer"><Icon kind="shield"/><div>Your workspace<small>One view across your devices.</small></div></div></aside>
  <div className="app-shell"><header className="topbar"><div className="breadcrumb">Workspace <span>/</span><strong>Overview</strong></div><div className="connection" data-state={connection}><span className="tiny-dot"/>{connection==='live'?'Live · connected':'Disconnected · retrying'}</div><button className="button button-quiet" onClick={()=>void api.POST('/api/auth/logout').then(()=>setAuth(false))}>Sign out</button></header><main id="main">
  <section id="overview" className="page-heading"><div><p className="eyebrow">YOUR AGENT WORKSPACE</p><h1>Your work, in motion<span>.</span></h1><p>A clear view of what’s running and what’s ready for you.</p></div><button className="button button-primary" onClick={()=>setAdding(true)}><Icon kind="plus"/>Track a task</button></section>
  <section className="capacity-card" data-progress={missing?'below':extra?'above':'met'} id="hero"><div><p className="eyebrow">PARALLEL TASKS</p><div className="capacity-number"><strong>{total}</strong><span>running<small>Minimum {minimum} · more is welcome</small></span></div><p id="capacity-message">{missing?'Start '+missing+' more tasks to reach your minimum of '+minimum+'.':extra?extra+' tasks above your minimum. Keep the momentum.':'Minimum met. More parallel tasks are welcome.'}</p></div><div className="capacity-visual"><div className="capacity-visual-heading"><span id="capacity-status">{missing?'Below minimum':extra?'Above minimum':'Minimum met'}</span><span>{Math.round(total/minimum*100)}% of minimum</span></div><div className="capacity-slots">{Array.from({length:Math.min(20,Math.max(total,minimum))},(_,i)=><span key={i} className={'capacity-slot '+(i<total?'filled ':'')+(i>=minimum?'extra':'')}><Icon kind={i<total?'activity':'plus'}/></span>)}</div><div className="capacity-legend"><span><i/>Running</span>{extra>0&&<span><i className="extra"/>Above minimum</span>}{missing>0&&<span><i className="open"/>Needed for minimum</span>}</div>{total>20&&<p>+{total-20} more running</p>}</div></section>
  <section className="sources">{Object.entries(snapshot?.sources??{}).map(([id,info])=><button key={id} className="source-card" aria-pressed={source===id} title={info.detail} onClick={()=>{setSource(source===id?'all':id);setLimit(5);}}><span className={'agent-icon '+id}><Icon kind={id}/></span><span className="source-name">{sourceName(id)}<small>{id==='copilot'?'Manual reports':id==='claude'?'Transcript + manual':'Auto-detected'}</small></span><span className="source-metric"><strong>{tasks.filter(t=>t.source===id&&t.status==='running').length}</strong><small>running</small></span></button>)}</section>
  <section className="devices-panel"><div className="section-heading"><h2>Devices <span className="count-badge">{devices.length}</span></h2><button className="button button-secondary" disabled={busy} onClick={()=>void run(async()=>setPairing(unwrap(await api.POST('/api/devices/pair'))))}><Icon kind="plus"/>Connect device</button></div><p className="section-description">One minimum across all online devices. Offline devices don’t count as running.</p><div className="device-list">{devices.map(d=><article className="device-card" key={d.id} data-status={d.status}><h3>{d.name}</h3><p><span className="device-state">{d.status}</span> · {d.runningCount} running</p><p>Last seen: {relative(d.lastSeenAt)}</p>{!d.local&&<button className="button button-quiet" disabled={busy} onClick={()=>void run(()=>api.DELETE('/api/devices/{id}',{params:{path:{id:d.id}}}).then(unwrap))}>Disconnect</button>}</article>)}</div><label className="device-filter">Show tasks from<select value={device} onChange={e=>{setDevice(e.target.value);setLimit(5);}}><option value="all">All devices</option>{devices.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label></section>
  <div className="work-grid"><div className="work-main"><section><div className="section-heading"><h2>In progress <span className="count-badge">{running.length}</span></h2><span className="section-caption"><span className="tiny-dot"/>Live activity</span></div><div className="task-toolbar"><button className="filter-button" onClick={()=>setSource('all')}>{source==='all'?'All agents':sourceName(source)}{source!=='all'&&<Icon kind="close"/>}</button><label className="search-field"><Icon kind="search"/><input aria-label="Search tasks" type="search" placeholder="Find a task…" value={query} onChange={e=>{setQuery(e.target.value);setLimit(5);}}/></label></div><div className="task-list">{running.map(t=><TaskCard key={t.id} task={t} inspect={()=>setDetail(t)} complete={t.managedLocally?()=>void run(()=>api.PATCH('/api/tasks/{id}',{params:{path:{id:t.id!}},body:{status:'completed',leaseMinutes:240}}).then(unwrap)):undefined}/>)}{!running.length&&<Empty title="No running tasks in this view" message="Start work with an agent or track a task to see it here."/>}</div>{unknown.length>0&&<section><h2 className="uncertain-heading">Activity to confirm</h2><p className="section-description">These sessions lack a reliable running signal and do not count toward the minimum.</p>{unknown.map(t=><TaskCard key={t.id} task={t} inspect={()=>setDetail(t)}/>)}</section>}</section>
  <section id="completed-panel" className="completed-panel"><div className="section-heading"><h2><button className="disclosure-button" aria-expanded={expanded} aria-controls="completed-content" onClick={()=>setExpanded(!expanded)}><span className="disclosure-icon"><Icon kind="chevron"/></span>Completed<span className="count-badge">{completions.length}</span></button></h2><button className="button button-quiet" disabled={busy||!completions.length} onClick={()=>void run(()=>api.DELETE('/api/completions').then(unwrap))}>Clear all</button></div>{expanded&&<div id="completed-content"><p className="section-description">Ready for your review. Clear a task to mark it as read.</p><div className="completed-list">{done.slice(0,limit).map(t=><article className="completion-row" key={t.id}><span className="completion-check"><Icon kind="check"/></span><div><h3><button className="task-title" onClick={()=>setDetail(t)}>{t.title}</button></h3><div className="completion-meta"><span>{t.deviceName}</span><span>· {sourceName(t.source)}</span><span>· {relative(t.completedAt)}</span><span>· {duration(t.startedAt,t.completedAt)}</span></div><p className="latest-output">{t.latestOutput||'Ready for review.'}</p></div><button className="clear-completion" disabled={busy} aria-label={'Clear completion: '+t.title} onClick={()=>void run(()=>api.DELETE('/api/completions/{id}',{params:{path:{id:t.id!}}}).then(unwrap))}><Icon kind="check"/>Clear</button></article>)}{!done.length&&<Empty title="You’re all caught up" message="Completed tasks will wait here for your review."/>}</div>{done.length>5&&<div className="completed-pagination"><span>Showing {Math.min(limit,done.length)} of {done.length}</span><div>{limit>5&&<button className="button button-quiet" onClick={()=>setLimit(5)}>Show less</button>}{limit<done.length&&<button className="button button-quiet" onClick={()=>setLimit(limit+5)}>Show {Math.min(5,done.length-limit)} more</button>}</div></div>}</div>}</section></div>
  <aside className="work-aside"><section id="settings-panel" className="settings-card"><h2>Keep the momentum</h2><p>Keep at least your chosen number of tasks running. More is welcome; reminders only appear below this minimum.</p><form id="settings-form" onSubmit={e=>{e.preventDefault();void run(async()=>{unwrap(await api.PUT('/api/settings',{body:settings}));setDirty(false);setSaved('Preferences saved');});}}><label htmlFor="minimum">Minimum parallel tasks</label><div className="stepper"><button type="button" aria-label="Decrease minimum" disabled={settings.minimumRunning<=1} onClick={()=>{setSettings({...settings,minimumRunning:settings.minimumRunning-1});setDirty(true);}}>−</button><input id="minimum" type="number" min="1" max="20" required value={settings.minimumRunning} onChange={e=>{setSettings({...settings,minimumRunning:Number(e.target.value)});setDirty(true);}}/><button type="button" aria-label="Increase minimum" disabled={settings.minimumRunning>=20} onClick={()=>{setSettings({...settings,minimumRunning:settings.minimumRunning+1});setDirty(true);}}>+</button></div><label htmlFor="cooldown">Remind me every</label><select id="cooldown" value={settings.reminderCooldownMinutes} onChange={e=>{setSettings({...settings,reminderCooldownMinutes:Number(e.target.value)});setDirty(true);}}>{[...new Set([5,15,30,60,settings.reminderCooldownMinutes])].sort((a,b)=>a-b).map(n=><option key={n} value={n}>{n} minutes</option>)}</select><button className="button button-secondary" disabled={busy}>Save preferences</button><p className="form-feedback" role="status">{dirty?'Unsaved changes':saved}</p></form><div className="settings-footnote"><Icon kind="shield"/>Reminders reach connected browsers.</div></section>{permission!==undefined&&<button className="button button-quiet notification-button" disabled={permission!=='default'} onClick={()=>void Notification.requestPermission().then(setPermission)}>{permission==='default'?'Enable browser reminders':permission==='granted'?'Browser reminders enabled':'Browser reminders blocked'}</button>}</aside></div><footer className="page-footer"><span>All systems, one workspace.</span><span>Agent Dashboard · Cross-platform</span></footer></main></div>
  {detail&&<Modal title={detail.title??'Task details'} close={closeDetail}><p className="detail-workspace">{detail.deviceName} · {detail.workspace}</p><p className="detail-time">{detail.status} · {duration(detail.startedAt,'completedAt' in detail?detail.completedAt:null)}</p><h3 className="detail-output-heading">Latest captured update</h3><pre id="detail-output">{detail.latestOutput||'No output captured yet.'}</pre></Modal>}
  {adding&&<Modal title="What are you working on?" close={closeAdd}><TaskForm devices={devices} submit={async body=>{unwrap(await api.POST('/api/tasks',{body}));setAdding(false);await refresh();}}/></Modal>}
  {pairing&&<Modal title="Connect another device" close={closePair}><p>Run the .NET collector on the other computer. Pairing expires at {new Date(pairing.expiresAt).toLocaleTimeString()}.</p><label className="pair-field">One-time code<input readOnly value={pairing.code}/></label><label className="pair-field">Enrollment command<textarea readOnly rows={5} value={'dotnet run --project src/Dashboard.Collector -- enroll --url '+(pairing.ingestionUrl??'YOUR_INGESTION_URL')+(pairing.tunnelId?' --tunnel-id '+pairing.tunnelId:'')+' --name "My device"'}/></label><p>Paste the code when prompted. Then run <code>dotnet run --project src/Dashboard.Collector -- run</code>.</p></Modal>}
  <div id="toast" className={toast?'show':''} role="status">{toast}</div></>;
}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
