import type { AgentTask, Device } from './api';
import { useState } from 'react';
import { Icon, duration, sourceName } from './ui';
export function TaskCard({task,inspect,complete}:{task:AgentTask;inspect:()=>void;complete?:()=>void}) {
  return <article className="task-card"><div className="task-card-top"><span className="task-agent"><span className={'agent-icon '+task.source}><Icon kind={task.source??'activity'}/></span>{sourceName(task.source)}<span className="tracking-label">{task.confidence}</span></span><span className="running-pill">{task.status}</span></div><h3><button className="task-title" onClick={inspect}>{task.title}</button></h3><p className="task-workspace" title={task.workspace??''}><Icon kind="folder"/><span>{task.workspace?.split(/[\\/]/).pop()||'No workspace'}</span></p><p className="task-device">{task.deviceName}</p><div className="output-preview"><div className="output-label"><Icon kind="message"/>Latest update</div><p className="latest-output">{task.latestOutput||'Waiting for the first update…'}</p></div><div className="task-card-footer"><span className="task-runtime"><Icon kind="clock"/>{duration(task.startedAt??task.createdAt)}</span><div className="task-actions">{complete&&<button className="button button-quiet" onClick={complete}>Complete</button>}<button className="button button-quiet" onClick={inspect}>View update →</button></div></div></article>;
}
type NewTask={source:string;title:string;workspace:string;latestOutput:string;leaseMinutes:number;deviceId:string};
export function TaskForm({devices,submit}:{devices:Device[];submit:(input:NewTask)=>Promise<void>}) {
  const [busy,setBusy]=useState(false),[error,setError]=useState('');
  return <form id="task-form" onSubmit={e=>{e.preventDefault();const form=new FormData(e.currentTarget);setBusy(true);void submit({source:String(form.get('source')),title:String(form.get('title')),workspace:String(form.get('workspace')),latestOutput:String(form.get('output')),leaseMinutes:Number(form.get('lease')),deviceId:String(form.get('device'))}).catch(e=>setError(String(e))).finally(()=>setBusy(false));}}><p>Track work when automatic lifecycle data is unavailable.</p><label>Agent<select name="source"><option value="copilot">GitHub Copilot</option><option value="claude">Claude Code</option><option value="codex">Codex</option></select></label><label>Device<select name="device"><option value="manual">Manually tracked</option>{devices.filter(d=>d.id!=='manual').map(d=><option value={d.id} key={d.id}>{d.name}</option>)}</select></label><label>Task name<input name="title" required maxLength={2000}/></label><label>Workspace<input name="workspace" maxLength={1000}/></label><label>Latest update<textarea name="output" maxLength={4000}/></label><label>Keep tracked for<select name="lease" defaultValue="240"><option value="60">1 hour</option><option value="240">4 hours</option><option value="480">8 hours</option></select></label><p className="form-error" role="alert">{error}</p><button className="button button-primary" disabled={busy}>Start tracking</button></form>;
}
